/**
 * Model Schema Definitions
 *
 * Each model has its own complete field definition.
 * When a user selects a model in the Agent Node, the fields are driven
 * by that model's schema definition.
 *
 * To add a new model or modify an existing one, edit its schema directly.
 * No inheritance - each model is self-contained.
 */

import type { FieldDefinition } from "@/components/nodes/CustomNode/types";
import { GEMINI_MODELS, DEFAULT_MODEL } from "@/lib/constants/models";

/**
 * Schema definition for a model's Agent Node fields.
 */
export interface ModelSchema {
  /** Model identifier (matches ModelOption.value) */
  modelId: string;
  /** Display label */
  label: string;
  /** Field IDs that are preserved when switching models */
  universalFieldIds: string[];
  /** Tab names for organizing fields */
  tabs: string[];
  /** Field definitions for this model */
  fields: FieldDefinition[];
}

/**
 * Universal field IDs that are always preserved when switching models.
 * Note: "location" is not included as it's now a project-level setting.
 */
const UNIVERSAL_FIELD_IDS = [
  "description",
  "model",
  "custom_model",
  "temperature",
];

/**
 * Vertex AI locations/regions for Gemini models.
 * Used by ProjectSettingsDialog for location selection.
 * @see https://cloud.google.com/vertex-ai/generative-ai/docs/learn/locations
 */
export const VERTEX_AI_LOCATIONS = [
  // Global
  { value: "global", label: "Global (Auto)" },
  // United States
  { value: "us-central1", label: "US Central (Iowa)" },
  { value: "us-east1", label: "US East (South Carolina)" },
  { value: "us-east4", label: "US East (N. Virginia)" },
  { value: "us-east5", label: "US East (Ohio)" },
  { value: "us-south1", label: "US South (Texas)" },
  { value: "us-west1", label: "US West (Oregon)" },
  { value: "us-west4", label: "US West (Nevada)" },
  // Canada
  { value: "northamerica-northeast1", label: "Canada (Montréal)" },
  // South America
  { value: "southamerica-east1", label: "South America (São Paulo)" },
  // Europe
  { value: "europe-west1", label: "Europe (Belgium)" },
  { value: "europe-west2", label: "Europe (London)" },
  { value: "europe-west3", label: "Europe (Frankfurt)" },
  { value: "europe-west4", label: "Europe (Netherlands)" },
  { value: "europe-west6", label: "Europe (Zürich)" },
  { value: "europe-west8", label: "Europe (Milan)" },
  { value: "europe-west9", label: "Europe (Paris)" },
  { value: "europe-southwest1", label: "Europe (Madrid)" },
  { value: "europe-north1", label: "Europe (Finland)" },
  { value: "europe-central2", label: "Europe (Warsaw)" },
  // Asia Pacific
  { value: "asia-northeast1", label: "Asia (Tokyo)" },
  { value: "asia-northeast3", label: "Asia (Seoul)" },
  { value: "asia-east1", label: "Asia (Taiwan)" },
  { value: "asia-east2", label: "Asia (Hong Kong)" },
  { value: "asia-south1", label: "Asia (Mumbai)" },
  { value: "asia-southeast1", label: "Asia (Singapore)" },
  { value: "australia-southeast1", label: "Australia (Sydney)" },
  // Middle East
  { value: "me-central1", label: "Middle East (Qatar)" },
  { value: "me-central2", label: "Middle East (Saudi Arabia)" },
  { value: "me-west1", label: "Middle East (Tel Aviv)" },
];

// =============================================================================
// MODEL SCHEMAS
// Each model has its complete field definition.
// =============================================================================

const GEMINI_2_5_FLASH_SCHEMA: ModelSchema = {
  modelId: "gemini-2.5-flash",
  label: "Gemini 2.5 Flash",
  universalFieldIds: UNIVERSAL_FIELD_IDS,
  tabs: ["General", "Execution", "Flow", "Schema", "Callbacks"],
  fields: [
    // === General Tab ===
    {
      id: "description",
      label: "Description",
      widget: "textarea",
      default: "",
      required: true,
      placeholder: "Describe what this agent does...",
      help_text: "A description of the agent's purpose (required for routing)",
      tab: "General",
    },
    {
      id: "model",
      label: "Model",
      widget: "select",
      default: DEFAULT_MODEL,
      options: GEMINI_MODELS,
      help_text: "The LLM model to use for this agent",
      tab: "General",
    },
    {
      id: "custom_model",
      label: "Custom Model",
      widget: "text",
      default: "",
      placeholder: "Custom model name",
      help_text: "Enter a custom model name",
      tab: "General",
      show_if: { model: "custom" },
    },
    {
      id: "location",
      label: "Location",
      widget: "info_display",
      help_text: "Set in Project Settings",
      tab: "General",
    },
    {
      id: "temperature",
      label: "Temperature",
      widget: "slider",
      default: 0.7,
      min_value: 0,
      max_value: 2,
      step: 0.1,
      help_text:
        "Controls randomness in responses (0 = deterministic, 2 = creative)",
      tab: "General",
    },
    // === Execution Tab ===
    {
      id: "planner_type",
      label: "Type",
      widget: "select",
      default: "none",
      options: [
        { value: "none", label: "None" },
        { value: "builtin", label: "Built-in (Thinking)" },
        { value: "react", label: "ReAct" },
      ],
      help_text: "The planning strategy for multi-step tasks",
      section: "Planner",
      tab: "Execution",
    },
    {
      id: "thinking_budget",
      label: "Thinking Budget",
      widget: "number",
      default: 2048,
      min_value: 0,
      help_text: "Maximum tokens for thinking/planning",
      section: "Planner",
      tab: "Execution",
      show_if: { planner_type: "builtin" },
    },
    {
      id: "include_thoughts",
      label: "Include thoughts in response",
      widget: "checkbox",
      default: false,
      help_text: "Include thinking output in the final response",
      section: "Planner",
      tab: "Execution",
      show_if: { planner_type: "builtin" },
    },
    {
      id: "code_executor_enabled",
      label: "Enable code execution",
      widget: "checkbox",
      default: false,
      help_text: "Allow this agent to execute generated code",
      section: "Code Executor",
      tab: "Execution",
    },
    {
      id: "code_executor_stateful",
      label: "Stateful (variables persist)",
      widget: "checkbox",
      default: false,
      help_text: "Variables persist between code executions",
      section: "Code Executor",
      tab: "Execution",
      show_if: { code_executor_enabled: true },
    },
    {
      id: "code_executor_error_retry",
      label: "Error Retry Attempts",
      widget: "number",
      default: 3,
      min_value: 0,
      max_value: 10,
      help_text: "Number of retry attempts on code execution errors",
      section: "Code Executor",
      tab: "Execution",
      show_if: { code_executor_enabled: true },
    },
    {
      id: "http_timeout",
      label: "Timeout (ms)",
      widget: "number",
      default: 30000,
      min_value: 0,
      step: 1000,
      help_text: "Request timeout in milliseconds",
      section: "HTTP Options",
      tab: "Execution",
    },
    {
      id: "http_max_retries",
      label: "Max Retries",
      widget: "number",
      default: 3,
      min_value: 0,
      max_value: 10,
      help_text: "Maximum number of retry attempts for failed requests",
      section: "HTTP Options",
      tab: "Execution",
    },
    {
      id: "http_retry_delay",
      label: "Retry Delay (ms)",
      widget: "number",
      default: 1000,
      min_value: 0,
      step: 100,
      help_text: "Initial delay between retries",
      section: "HTTP Options",
      tab: "Execution",
    },
    {
      id: "http_backoff_multiplier",
      label: "Backoff Multiplier",
      widget: "number",
      default: 2,
      min_value: 1,
      max_value: 5,
      step: 0.5,
      help_text: "Exponential backoff multiplier for retries",
      section: "HTTP Options",
      tab: "Execution",
    },
    // === Flow Tab ===
    {
      id: "disallow_transfer_to_parent",
      label: "Disallow transfer to parent",
      widget: "checkbox",
      default: false,
      help_text:
        "Prevent this agent from transferring control back to its parent",
      section: "Transfer Controls",
      tab: "Flow",
    },
    {
      id: "disallow_transfer_to_peers",
      label: "Disallow transfer to peers",
      widget: "checkbox",
      default: false,
      help_text:
        "Prevent this agent from transferring control to sibling agents",
      section: "Transfer Controls",
      tab: "Flow",
    },
    // === Schema Tab ===
    {
      id: "output_key",
      label: "Output Key",
      widget: "text",
      default: "",
      placeholder: "e.g., result",
      help_text: "Saves agent output to session state with this key",
      section: "Output Options",
      tab: "Schema",
    },
    {
      id: "include_contents",
      label: "Include Contents",
      widget: "select",
      default: "default",
      options: [
        { value: "default", label: "Default" },
        { value: "none", label: "None" },
      ],
      help_text: "Controls content inclusion in agent processing",
      section: "Output Options",
      tab: "Schema",
    },
    {
      id: "input_schema",
      label: "Input Schema",
      widget: "text",
      default: "",
      placeholder: "e.g., models.TaskInput",
      help_text: "Pydantic BaseModel class path",
      section: "Schema Validation",
      tab: "Schema",
    },
    {
      id: "output_schema",
      label: "Output Schema",
      widget: "text",
      default: "",
      placeholder: "e.g., models.TaskOutput",
      help_text: "Pydantic BaseModel class path",
      section: "Schema Validation",
      tab: "Schema",
    },
    // === Callbacks Tab ===
    {
      id: "before_model_callback",
      label: "Before Model Callback",
      widget: "text",
      default: "",
      placeholder: "e.g., callbacks/guardrails.py",
      help_text: "Callback function to run before model invocation",
      section: "Model Callbacks",
      tab: "Callbacks",
    },
    {
      id: "after_model_callback",
      label: "After Model Callback",
      widget: "text",
      default: "",
      placeholder: "e.g., callbacks/logging.py",
      help_text: "Callback function to run after model invocation",
      section: "Model Callbacks",
      tab: "Callbacks",
    },
    {
      id: "before_tool_callback",
      label: "Before Tool Callback",
      widget: "text",
      default: "",
      placeholder: "e.g., callbacks/validation.py",
      help_text: "Callback function to run before tool execution",
      section: "Tool Callbacks",
      tab: "Callbacks",
    },
    {
      id: "after_tool_callback",
      label: "After Tool Callback",
      widget: "text",
      default: "",
      placeholder: "e.g., callbacks/artifact_save.py",
      help_text: "Callback function to run after tool execution",
      section: "Tool Callbacks",
      tab: "Callbacks",
    },
  ],
};

const GEMINI_2_5_PRO_SCHEMA: ModelSchema = {
  modelId: "gemini-2.5-pro",
  label: "Gemini 2.5 Pro",
  universalFieldIds: UNIVERSAL_FIELD_IDS,
  tabs: ["General", "Execution", "Flow", "Schema", "Callbacks"],
  fields: [
    // === General Tab ===
    {
      id: "description",
      label: "Description",
      widget: "textarea",
      default: "",
      required: true,
      placeholder: "Describe what this agent does...",
      help_text: "A description of the agent's purpose (required for routing)",
      tab: "General",
    },
    {
      id: "model",
      label: "Model",
      widget: "select",
      default: DEFAULT_MODEL,
      options: GEMINI_MODELS,
      help_text: "The LLM model to use for this agent",
      tab: "General",
    },
    {
      id: "custom_model",
      label: "Custom Model",
      widget: "text",
      default: "",
      placeholder: "Custom model name",
      help_text: "Enter a custom model name",
      tab: "General",
      show_if: { model: "custom" },
    },
    {
      id: "location",
      label: "Location",
      widget: "info_display",
      help_text: "Set in Project Settings",
      tab: "General",
    },
    {
      id: "temperature",
      label: "Temperature",
      widget: "slider",
      default: 0.7,
      min_value: 0,
      max_value: 2,
      step: 0.1,
      help_text:
        "Controls randomness in responses (0 = deterministic, 2 = creative)",
      tab: "General",
    },
    // === Execution Tab ===
    {
      id: "planner_type",
      label: "Type",
      widget: "select",
      default: "none",
      options: [
        { value: "none", label: "None" },
        { value: "builtin", label: "Built-in (Thinking)" },
        { value: "react", label: "ReAct" },
      ],
      help_text: "The planning strategy for multi-step tasks",
      section: "Planner",
      tab: "Execution",
    },
    {
      id: "thinking_budget",
      label: "Thinking Budget",
      widget: "number",
      default: 2048,
      min_value: 0,
      help_text: "Maximum tokens for thinking/planning",
      section: "Planner",
      tab: "Execution",
      show_if: { planner_type: "builtin" },
    },
    {
      id: "include_thoughts",
      label: "Include thoughts in response",
      widget: "checkbox",
      default: false,
      help_text: "Include thinking output in the final response",
      section: "Planner",
      tab: "Execution",
      show_if: { planner_type: "builtin" },
    },
    {
      id: "code_executor_enabled",
      label: "Enable code execution",
      widget: "checkbox",
      default: false,
      help_text: "Allow this agent to execute generated code",
      section: "Code Executor",
      tab: "Execution",
    },
    {
      id: "code_executor_stateful",
      label: "Stateful (variables persist)",
      widget: "checkbox",
      default: false,
      help_text: "Variables persist between code executions",
      section: "Code Executor",
      tab: "Execution",
      show_if: { code_executor_enabled: true },
    },
    {
      id: "code_executor_error_retry",
      label: "Error Retry Attempts",
      widget: "number",
      default: 3,
      min_value: 0,
      max_value: 10,
      help_text: "Number of retry attempts on code execution errors",
      section: "Code Executor",
      tab: "Execution",
      show_if: { code_executor_enabled: true },
    },
    {
      id: "http_timeout",
      label: "Timeout (ms)",
      widget: "number",
      default: 30000,
      min_value: 0,
      step: 1000,
      help_text: "Request timeout in milliseconds",
      section: "HTTP Options",
      tab: "Execution",
    },
    {
      id: "http_max_retries",
      label: "Max Retries",
      widget: "number",
      default: 3,
      min_value: 0,
      max_value: 10,
      help_text: "Maximum number of retry attempts for failed requests",
      section: "HTTP Options",
      tab: "Execution",
    },
    {
      id: "http_retry_delay",
      label: "Retry Delay (ms)",
      widget: "number",
      default: 1000,
      min_value: 0,
      step: 100,
      help_text: "Initial delay between retries",
      section: "HTTP Options",
      tab: "Execution",
    },
    {
      id: "http_backoff_multiplier",
      label: "Backoff Multiplier",
      widget: "number",
      default: 2,
      min_value: 1,
      max_value: 5,
      step: 0.5,
      help_text: "Exponential backoff multiplier for retries",
      section: "HTTP Options",
      tab: "Execution",
    },
    // === Flow Tab ===
    {
      id: "disallow_transfer_to_parent",
      label: "Disallow transfer to parent",
      widget: "checkbox",
      default: false,
      help_text:
        "Prevent this agent from transferring control back to its parent",
      section: "Transfer Controls",
      tab: "Flow",
    },
    {
      id: "disallow_transfer_to_peers",
      label: "Disallow transfer to peers",
      widget: "checkbox",
      default: false,
      help_text:
        "Prevent this agent from transferring control to sibling agents",
      section: "Transfer Controls",
      tab: "Flow",
    },
    // === Schema Tab ===
    {
      id: "output_key",
      label: "Output Key",
      widget: "text",
      default: "",
      placeholder: "e.g., result",
      help_text: "Saves agent output to session state with this key",
      section: "Output Options",
      tab: "Schema",
    },
    {
      id: "include_contents",
      label: "Include Contents",
      widget: "select",
      default: "default",
      options: [
        { value: "default", label: "Default" },
        { value: "none", label: "None" },
      ],
      help_text: "Controls content inclusion in agent processing",
      section: "Output Options",
      tab: "Schema",
    },
    {
      id: "input_schema",
      label: "Input Schema",
      widget: "text",
      default: "",
      placeholder: "e.g., models.TaskInput",
      help_text: "Pydantic BaseModel class path",
      section: "Schema Validation",
      tab: "Schema",
    },
    {
      id: "output_schema",
      label: "Output Schema",
      widget: "text",
      default: "",
      placeholder: "e.g., models.TaskOutput",
      help_text: "Pydantic BaseModel class path",
      section: "Schema Validation",
      tab: "Schema",
    },
    // === Callbacks Tab ===
    {
      id: "before_model_callback",
      label: "Before Model Callback",
      widget: "text",
      default: "",
      placeholder: "e.g., callbacks/guardrails.py",
      help_text: "Callback function to run before model invocation",
      section: "Model Callbacks",
      tab: "Callbacks",
    },
    {
      id: "after_model_callback",
      label: "After Model Callback",
      widget: "text",
      default: "",
      placeholder: "e.g., callbacks/logging.py",
      help_text: "Callback function to run after model invocation",
      section: "Model Callbacks",
      tab: "Callbacks",
    },
    {
      id: "before_tool_callback",
      label: "Before Tool Callback",
      widget: "text",
      default: "",
      placeholder: "e.g., callbacks/validation.py",
      help_text: "Callback function to run before tool execution",
      section: "Tool Callbacks",
      tab: "Callbacks",
    },
    {
      id: "after_tool_callback",
      label: "After Tool Callback",
      widget: "text",
      default: "",
      placeholder: "e.g., callbacks/artifact_save.py",
      help_text: "Callback function to run after tool execution",
      section: "Tool Callbacks",
      tab: "Callbacks",
    },
  ],
};

const GEMINI_2_0_FLASH_EXP_SCHEMA: ModelSchema = {
  modelId: "gemini-2.0-flash-exp",
  label: "Gemini 2.0 Flash Exp",
  universalFieldIds: UNIVERSAL_FIELD_IDS,
  tabs: ["General", "Execution", "Flow", "Schema", "Callbacks"],
  fields: [
    // === General Tab ===
    {
      id: "description",
      label: "Description",
      widget: "textarea",
      default: "",
      required: true,
      placeholder: "Describe what this agent does...",
      help_text: "A description of the agent's purpose (required for routing)",
      tab: "General",
    },
    {
      id: "model",
      label: "Model",
      widget: "select",
      default: DEFAULT_MODEL,
      options: GEMINI_MODELS,
      help_text: "The LLM model to use for this agent",
      tab: "General",
    },
    {
      id: "custom_model",
      label: "Custom Model",
      widget: "text",
      default: "",
      placeholder: "Custom model name",
      help_text: "Enter a custom model name",
      tab: "General",
      show_if: { model: "custom" },
    },
    {
      id: "location",
      label: "Location",
      widget: "info_display",
      help_text: "Set in Project Settings",
      tab: "General",
    },
    {
      id: "temperature",
      label: "Temperature",
      widget: "slider",
      default: 0.7,
      min_value: 0,
      max_value: 2,
      step: 0.1,
      help_text:
        "Controls randomness in responses (0 = deterministic, 2 = creative)",
      tab: "General",
    },
    // === Execution Tab ===
    {
      id: "planner_type",
      label: "Type",
      widget: "select",
      default: "none",
      options: [
        { value: "none", label: "None" },
        { value: "builtin", label: "Built-in (Thinking)" },
        { value: "react", label: "ReAct" },
      ],
      help_text: "The planning strategy for multi-step tasks",
      section: "Planner",
      tab: "Execution",
    },
    {
      id: "thinking_budget",
      label: "Thinking Budget",
      widget: "number",
      default: 2048,
      min_value: 0,
      help_text: "Maximum tokens for thinking/planning",
      section: "Planner",
      tab: "Execution",
      show_if: { planner_type: "builtin" },
    },
    {
      id: "include_thoughts",
      label: "Include thoughts in response",
      widget: "checkbox",
      default: false,
      help_text: "Include thinking output in the final response",
      section: "Planner",
      tab: "Execution",
      show_if: { planner_type: "builtin" },
    },
    {
      id: "code_executor_enabled",
      label: "Enable code execution",
      widget: "checkbox",
      default: false,
      help_text: "Allow this agent to execute generated code",
      section: "Code Executor",
      tab: "Execution",
    },
    {
      id: "code_executor_stateful",
      label: "Stateful (variables persist)",
      widget: "checkbox",
      default: false,
      help_text: "Variables persist between code executions",
      section: "Code Executor",
      tab: "Execution",
      show_if: { code_executor_enabled: true },
    },
    {
      id: "code_executor_error_retry",
      label: "Error Retry Attempts",
      widget: "number",
      default: 3,
      min_value: 0,
      max_value: 10,
      help_text: "Number of retry attempts on code execution errors",
      section: "Code Executor",
      tab: "Execution",
      show_if: { code_executor_enabled: true },
    },
    {
      id: "http_timeout",
      label: "Timeout (ms)",
      widget: "number",
      default: 30000,
      min_value: 0,
      step: 1000,
      help_text: "Request timeout in milliseconds",
      section: "HTTP Options",
      tab: "Execution",
    },
    {
      id: "http_max_retries",
      label: "Max Retries",
      widget: "number",
      default: 3,
      min_value: 0,
      max_value: 10,
      help_text: "Maximum number of retry attempts for failed requests",
      section: "HTTP Options",
      tab: "Execution",
    },
    {
      id: "http_retry_delay",
      label: "Retry Delay (ms)",
      widget: "number",
      default: 1000,
      min_value: 0,
      step: 100,
      help_text: "Initial delay between retries",
      section: "HTTP Options",
      tab: "Execution",
    },
    {
      id: "http_backoff_multiplier",
      label: "Backoff Multiplier",
      widget: "number",
      default: 2,
      min_value: 1,
      max_value: 5,
      step: 0.5,
      help_text: "Exponential backoff multiplier for retries",
      section: "HTTP Options",
      tab: "Execution",
    },
    // === Flow Tab ===
    {
      id: "disallow_transfer_to_parent",
      label: "Disallow transfer to parent",
      widget: "checkbox",
      default: false,
      help_text:
        "Prevent this agent from transferring control back to its parent",
      section: "Transfer Controls",
      tab: "Flow",
    },
    {
      id: "disallow_transfer_to_peers",
      label: "Disallow transfer to peers",
      widget: "checkbox",
      default: false,
      help_text:
        "Prevent this agent from transferring control to sibling agents",
      section: "Transfer Controls",
      tab: "Flow",
    },
    // === Schema Tab ===
    {
      id: "output_key",
      label: "Output Key",
      widget: "text",
      default: "",
      placeholder: "e.g., result",
      help_text: "Saves agent output to session state with this key",
      section: "Output Options",
      tab: "Schema",
    },
    {
      id: "include_contents",
      label: "Include Contents",
      widget: "select",
      default: "default",
      options: [
        { value: "default", label: "Default" },
        { value: "none", label: "None" },
      ],
      help_text: "Controls content inclusion in agent processing",
      section: "Output Options",
      tab: "Schema",
    },
    {
      id: "input_schema",
      label: "Input Schema",
      widget: "text",
      default: "",
      placeholder: "e.g., models.TaskInput",
      help_text: "Pydantic BaseModel class path",
      section: "Schema Validation",
      tab: "Schema",
    },
    {
      id: "output_schema",
      label: "Output Schema",
      widget: "text",
      default: "",
      placeholder: "e.g., models.TaskOutput",
      help_text: "Pydantic BaseModel class path",
      section: "Schema Validation",
      tab: "Schema",
    },
    // === Callbacks Tab ===
    {
      id: "before_model_callback",
      label: "Before Model Callback",
      widget: "text",
      default: "",
      placeholder: "e.g., callbacks/guardrails.py",
      help_text: "Callback function to run before model invocation",
      section: "Model Callbacks",
      tab: "Callbacks",
    },
    {
      id: "after_model_callback",
      label: "After Model Callback",
      widget: "text",
      default: "",
      placeholder: "e.g., callbacks/logging.py",
      help_text: "Callback function to run after model invocation",
      section: "Model Callbacks",
      tab: "Callbacks",
    },
    {
      id: "before_tool_callback",
      label: "Before Tool Callback",
      widget: "text",
      default: "",
      placeholder: "e.g., callbacks/validation.py",
      help_text: "Callback function to run before tool execution",
      section: "Tool Callbacks",
      tab: "Callbacks",
    },
    {
      id: "after_tool_callback",
      label: "After Tool Callback",
      widget: "text",
      default: "",
      placeholder: "e.g., callbacks/artifact_save.py",
      help_text: "Callback function to run after tool execution",
      section: "Tool Callbacks",
      tab: "Callbacks",
    },
  ],
};

const GEMINI_2_0_FLASH_SCHEMA: ModelSchema = {
  modelId: "gemini-2.0-flash",
  label: "Gemini 2.0 Flash",
  universalFieldIds: UNIVERSAL_FIELD_IDS,
  tabs: ["General", "Execution", "Flow", "Schema", "Callbacks"],
  fields: [
    // === General Tab ===
    {
      id: "description",
      label: "Description",
      widget: "textarea",
      default: "",
      required: true,
      placeholder: "Describe what this agent does...",
      help_text: "A description of the agent's purpose (required for routing)",
      tab: "General",
    },
    {
      id: "model",
      label: "Model",
      widget: "select",
      default: DEFAULT_MODEL,
      options: GEMINI_MODELS,
      help_text: "The LLM model to use for this agent",
      tab: "General",
    },
    {
      id: "custom_model",
      label: "Custom Model",
      widget: "text",
      default: "",
      placeholder: "Custom model name",
      help_text: "Enter a custom model name",
      tab: "General",
      show_if: { model: "custom" },
    },
    {
      id: "location",
      label: "Location",
      widget: "info_display",
      help_text: "Set in Project Settings",
      tab: "General",
    },
    {
      id: "temperature",
      label: "Temperature",
      widget: "slider",
      default: 0.7,
      min_value: 0,
      max_value: 2,
      step: 0.1,
      help_text:
        "Controls randomness in responses (0 = deterministic, 2 = creative)",
      tab: "General",
    },
    // === Execution Tab ===
    {
      id: "planner_type",
      label: "Type",
      widget: "select",
      default: "none",
      options: [
        { value: "none", label: "None" },
        { value: "builtin", label: "Built-in (Thinking)" },
        { value: "react", label: "ReAct" },
      ],
      help_text: "The planning strategy for multi-step tasks",
      section: "Planner",
      tab: "Execution",
    },
    {
      id: "thinking_budget",
      label: "Thinking Budget",
      widget: "number",
      default: 2048,
      min_value: 0,
      help_text: "Maximum tokens for thinking/planning",
      section: "Planner",
      tab: "Execution",
      show_if: { planner_type: "builtin" },
    },
    {
      id: "include_thoughts",
      label: "Include thoughts in response",
      widget: "checkbox",
      default: false,
      help_text: "Include thinking output in the final response",
      section: "Planner",
      tab: "Execution",
      show_if: { planner_type: "builtin" },
    },
    {
      id: "code_executor_enabled",
      label: "Enable code execution",
      widget: "checkbox",
      default: false,
      help_text: "Allow this agent to execute generated code",
      section: "Code Executor",
      tab: "Execution",
    },
    {
      id: "code_executor_stateful",
      label: "Stateful (variables persist)",
      widget: "checkbox",
      default: false,
      help_text: "Variables persist between code executions",
      section: "Code Executor",
      tab: "Execution",
      show_if: { code_executor_enabled: true },
    },
    {
      id: "code_executor_error_retry",
      label: "Error Retry Attempts",
      widget: "number",
      default: 3,
      min_value: 0,
      max_value: 10,
      help_text: "Number of retry attempts on code execution errors",
      section: "Code Executor",
      tab: "Execution",
      show_if: { code_executor_enabled: true },
    },
    {
      id: "http_timeout",
      label: "Timeout (ms)",
      widget: "number",
      default: 30000,
      min_value: 0,
      step: 1000,
      help_text: "Request timeout in milliseconds",
      section: "HTTP Options",
      tab: "Execution",
    },
    {
      id: "http_max_retries",
      label: "Max Retries",
      widget: "number",
      default: 3,
      min_value: 0,
      max_value: 10,
      help_text: "Maximum number of retry attempts for failed requests",
      section: "HTTP Options",
      tab: "Execution",
    },
    {
      id: "http_retry_delay",
      label: "Retry Delay (ms)",
      widget: "number",
      default: 1000,
      min_value: 0,
      step: 100,
      help_text: "Initial delay between retries",
      section: "HTTP Options",
      tab: "Execution",
    },
    {
      id: "http_backoff_multiplier",
      label: "Backoff Multiplier",
      widget: "number",
      default: 2,
      min_value: 1,
      max_value: 5,
      step: 0.5,
      help_text: "Exponential backoff multiplier for retries",
      section: "HTTP Options",
      tab: "Execution",
    },
    // === Flow Tab ===
    {
      id: "disallow_transfer_to_parent",
      label: "Disallow transfer to parent",
      widget: "checkbox",
      default: false,
      help_text:
        "Prevent this agent from transferring control back to its parent",
      section: "Transfer Controls",
      tab: "Flow",
    },
    {
      id: "disallow_transfer_to_peers",
      label: "Disallow transfer to peers",
      widget: "checkbox",
      default: false,
      help_text:
        "Prevent this agent from transferring control to sibling agents",
      section: "Transfer Controls",
      tab: "Flow",
    },
    // === Schema Tab ===
    {
      id: "output_key",
      label: "Output Key",
      widget: "text",
      default: "",
      placeholder: "e.g., result",
      help_text: "Saves agent output to session state with this key",
      section: "Output Options",
      tab: "Schema",
    },
    {
      id: "include_contents",
      label: "Include Contents",
      widget: "select",
      default: "default",
      options: [
        { value: "default", label: "Default" },
        { value: "none", label: "None" },
      ],
      help_text: "Controls content inclusion in agent processing",
      section: "Output Options",
      tab: "Schema",
    },
    {
      id: "input_schema",
      label: "Input Schema",
      widget: "text",
      default: "",
      placeholder: "e.g., models.TaskInput",
      help_text: "Pydantic BaseModel class path",
      section: "Schema Validation",
      tab: "Schema",
    },
    {
      id: "output_schema",
      label: "Output Schema",
      widget: "text",
      default: "",
      placeholder: "e.g., models.TaskOutput",
      help_text: "Pydantic BaseModel class path",
      section: "Schema Validation",
      tab: "Schema",
    },
    // === Callbacks Tab ===
    {
      id: "before_model_callback",
      label: "Before Model Callback",
      widget: "text",
      default: "",
      placeholder: "e.g., callbacks/guardrails.py",
      help_text: "Callback function to run before model invocation",
      section: "Model Callbacks",
      tab: "Callbacks",
    },
    {
      id: "after_model_callback",
      label: "After Model Callback",
      widget: "text",
      default: "",
      placeholder: "e.g., callbacks/logging.py",
      help_text: "Callback function to run after model invocation",
      section: "Model Callbacks",
      tab: "Callbacks",
    },
    {
      id: "before_tool_callback",
      label: "Before Tool Callback",
      widget: "text",
      default: "",
      placeholder: "e.g., callbacks/validation.py",
      help_text: "Callback function to run before tool execution",
      section: "Tool Callbacks",
      tab: "Callbacks",
    },
    {
      id: "after_tool_callback",
      label: "After Tool Callback",
      widget: "text",
      default: "",
      placeholder: "e.g., callbacks/artifact_save.py",
      help_text: "Callback function to run after tool execution",
      section: "Tool Callbacks",
      tab: "Callbacks",
    },
  ],
};

const GEMINI_3_FLASH_PREVIEW_SCHEMA: ModelSchema = {
  modelId: "gemini-3-flash-preview",
  label: "Gemini 3 Flash (prev)",
  universalFieldIds: UNIVERSAL_FIELD_IDS,
  tabs: ["General", "Execution", "Flow", "Schema", "Callbacks"],
  fields: [
    // === General Tab ===
    {
      id: "description",
      label: "Description",
      widget: "textarea",
      default: "",
      required: true,
      placeholder: "Describe what this agent does...",
      help_text: "A description of the agent's purpose (required for routing)",
      tab: "General",
    },
    {
      id: "model",
      label: "Model",
      widget: "select",
      default: DEFAULT_MODEL,
      options: GEMINI_MODELS,
      help_text: "The LLM model to use for this agent",
      tab: "General",
    },
    {
      id: "custom_model",
      label: "Custom Model",
      widget: "text",
      default: "",
      placeholder: "Custom model name",
      help_text: "Enter a custom model name",
      tab: "General",
      show_if: { model: "custom" },
    },
    {
      id: "location",
      label: "Location",
      widget: "info_display",
      help_text: "Set in Project Settings",
      tab: "General",
    },
    {
      id: "temperature",
      label: "Temperature",
      widget: "slider",
      default: 1,
      min_value: 0,
      max_value: 2,
      step: 0.1,
      help_text:
        "Controls randomness in responses (0 = deterministic, 2 = creative). Note: For Gemini 3 models, temperatures below 1 are not recommended and may cause unexpected behavior.",
      tab: "General",
    },
    // === Execution Tab ===
    {
      id: "planner_type",
      label: "Type",
      widget: "select",
      default: "none",
      options: [
        { value: "none", label: "None" },
        { value: "builtin", label: "Built-in (Thinking)" },
        { value: "react", label: "ReAct" },
      ],
      help_text: "The planning strategy for multi-step tasks",
      section: "Planner",
      tab: "Execution",
    },
    {
      id: "thinking_level",
      label: "Thinking Level",
      widget: "select",
      default: "medium",
      options: [
        { value: "minimal", label: "Minimal" },
        { value: "low", label: "Low" },
        { value: "medium", label: "Medium" },
        { value: "high", label: "High" },
      ],
      help_text: "Controls the depth of reasoning for thinking/planning",
      section: "Planner",
      tab: "Execution",
      show_if: { planner_type: "builtin" },
    },
    {
      id: "include_thoughts",
      label: "Include thoughts in response",
      widget: "checkbox",
      default: false,
      help_text: "Include thinking output in the final response",
      section: "Planner",
      tab: "Execution",
      show_if: { planner_type: "builtin" },
    },
    {
      id: "code_executor_enabled",
      label: "Enable code execution",
      widget: "checkbox",
      default: false,
      help_text: "Allow this agent to execute generated code",
      section: "Code Executor",
      tab: "Execution",
    },
    {
      id: "code_executor_stateful",
      label: "Stateful (variables persist)",
      widget: "checkbox",
      default: false,
      help_text: "Variables persist between code executions",
      section: "Code Executor",
      tab: "Execution",
      show_if: { code_executor_enabled: true },
    },
    {
      id: "code_executor_error_retry",
      label: "Error Retry Attempts",
      widget: "number",
      default: 3,
      min_value: 0,
      max_value: 10,
      help_text: "Number of retry attempts on code execution errors",
      section: "Code Executor",
      tab: "Execution",
      show_if: { code_executor_enabled: true },
    },
    {
      id: "http_timeout",
      label: "Timeout (ms)",
      widget: "number",
      default: 30000,
      min_value: 0,
      step: 1000,
      help_text: "Request timeout in milliseconds",
      section: "HTTP Options",
      tab: "Execution",
    },
    {
      id: "http_max_retries",
      label: "Max Retries",
      widget: "number",
      default: 3,
      min_value: 0,
      max_value: 10,
      help_text: "Maximum number of retry attempts for failed requests",
      section: "HTTP Options",
      tab: "Execution",
    },
    {
      id: "http_retry_delay",
      label: "Retry Delay (ms)",
      widget: "number",
      default: 1000,
      min_value: 0,
      step: 100,
      help_text: "Initial delay between retries",
      section: "HTTP Options",
      tab: "Execution",
    },
    {
      id: "http_backoff_multiplier",
      label: "Backoff Multiplier",
      widget: "number",
      default: 2,
      min_value: 1,
      max_value: 5,
      step: 0.5,
      help_text: "Exponential backoff multiplier for retries",
      section: "HTTP Options",
      tab: "Execution",
    },
    // === Flow Tab ===
    {
      id: "disallow_transfer_to_parent",
      label: "Disallow transfer to parent",
      widget: "checkbox",
      default: false,
      help_text:
        "Prevent this agent from transferring control back to its parent",
      section: "Transfer Controls",
      tab: "Flow",
    },
    {
      id: "disallow_transfer_to_peers",
      label: "Disallow transfer to peers",
      widget: "checkbox",
      default: false,
      help_text:
        "Prevent this agent from transferring control to sibling agents",
      section: "Transfer Controls",
      tab: "Flow",
    },
    // === Schema Tab ===
    {
      id: "output_key",
      label: "Output Key",
      widget: "text",
      default: "",
      placeholder: "e.g., result",
      help_text: "Saves agent output to session state with this key",
      section: "Output Options",
      tab: "Schema",
    },
    {
      id: "include_contents",
      label: "Include Contents",
      widget: "select",
      default: "default",
      options: [
        { value: "default", label: "Default" },
        { value: "none", label: "None" },
      ],
      help_text: "Controls content inclusion in agent processing",
      section: "Output Options",
      tab: "Schema",
    },
    {
      id: "input_schema",
      label: "Input Schema",
      widget: "text",
      default: "",
      placeholder: "e.g., models.TaskInput",
      help_text: "Pydantic BaseModel class path",
      section: "Schema Validation",
      tab: "Schema",
    },
    {
      id: "output_schema",
      label: "Output Schema",
      widget: "text",
      default: "",
      placeholder: "e.g., models.TaskOutput",
      help_text: "Pydantic BaseModel class path",
      section: "Schema Validation",
      tab: "Schema",
    },
    // === Callbacks Tab ===
    {
      id: "before_model_callback",
      label: "Before Model Callback",
      widget: "text",
      default: "",
      placeholder: "e.g., callbacks/guardrails.py",
      help_text: "Callback function to run before model invocation",
      section: "Model Callbacks",
      tab: "Callbacks",
    },
    {
      id: "after_model_callback",
      label: "After Model Callback",
      widget: "text",
      default: "",
      placeholder: "e.g., callbacks/logging.py",
      help_text: "Callback function to run after model invocation",
      section: "Model Callbacks",
      tab: "Callbacks",
    },
    {
      id: "before_tool_callback",
      label: "Before Tool Callback",
      widget: "text",
      default: "",
      placeholder: "e.g., callbacks/validation.py",
      help_text: "Callback function to run before tool execution",
      section: "Tool Callbacks",
      tab: "Callbacks",
    },
    {
      id: "after_tool_callback",
      label: "After Tool Callback",
      widget: "text",
      default: "",
      placeholder: "e.g., callbacks/artifact_save.py",
      help_text: "Callback function to run after tool execution",
      section: "Tool Callbacks",
      tab: "Callbacks",
    },
  ],
};

const GEMINI_3_PRO_PREVIEW_SCHEMA: ModelSchema = {
  modelId: "gemini-3-pro-preview",
  label: "Gemini 3 Pro (prev)",
  universalFieldIds: UNIVERSAL_FIELD_IDS,
  tabs: ["General", "Execution", "Flow", "Schema", "Callbacks"],
  fields: [
    // === General Tab ===
    {
      id: "description",
      label: "Description",
      widget: "textarea",
      default: "",
      required: true,
      placeholder: "Describe what this agent does...",
      help_text: "A description of the agent's purpose (required for routing)",
      tab: "General",
    },
    {
      id: "model",
      label: "Model",
      widget: "select",
      default: DEFAULT_MODEL,
      options: GEMINI_MODELS,
      help_text: "The LLM model to use for this agent",
      tab: "General",
    },
    {
      id: "custom_model",
      label: "Custom Model",
      widget: "text",
      default: "",
      placeholder: "Custom model name",
      help_text: "Enter a custom model name",
      tab: "General",
      show_if: { model: "custom" },
    },
    {
      id: "location",
      label: "Location",
      widget: "info_display",
      help_text: "Set in Project Settings",
      tab: "General",
    },
    {
      id: "temperature",
      label: "Temperature",
      widget: "slider",
      default: 1,
      min_value: 0,
      max_value: 2,
      step: 0.1,
      help_text:
        "Controls randomness in responses (0 = deterministic, 2 = creative). Note: For Gemini 3 models, temperatures below 1 are not recommended and may cause unexpected behavior.",
      tab: "General",
    },
    // === Execution Tab ===
    {
      id: "planner_type",
      label: "Type",
      widget: "select",
      default: "none",
      options: [
        { value: "none", label: "None" },
        { value: "builtin", label: "Built-in (Thinking)" },
        { value: "react", label: "ReAct" },
      ],
      help_text: "The planning strategy for multi-step tasks",
      section: "Planner",
      tab: "Execution",
    },
    {
      id: "thinking_level",
      label: "Thinking Level",
      widget: "select",
      default: "medium",
      options: [
        { value: "minimal", label: "Minimal" },
        { value: "low", label: "Low" },
        { value: "medium", label: "Medium" },
        { value: "high", label: "High" },
      ],
      help_text: "Controls the depth of reasoning for thinking/planning",
      section: "Planner",
      tab: "Execution",
      show_if: { planner_type: "builtin" },
    },
    {
      id: "include_thoughts",
      label: "Include thoughts in response",
      widget: "checkbox",
      default: false,
      help_text: "Include thinking output in the final response",
      section: "Planner",
      tab: "Execution",
      show_if: { planner_type: "builtin" },
    },
    {
      id: "code_executor_enabled",
      label: "Enable code execution",
      widget: "checkbox",
      default: false,
      help_text: "Allow this agent to execute generated code",
      section: "Code Executor",
      tab: "Execution",
    },
    {
      id: "code_executor_stateful",
      label: "Stateful (variables persist)",
      widget: "checkbox",
      default: false,
      help_text: "Variables persist between code executions",
      section: "Code Executor",
      tab: "Execution",
      show_if: { code_executor_enabled: true },
    },
    {
      id: "code_executor_error_retry",
      label: "Error Retry Attempts",
      widget: "number",
      default: 3,
      min_value: 0,
      max_value: 10,
      help_text: "Number of retry attempts on code execution errors",
      section: "Code Executor",
      tab: "Execution",
      show_if: { code_executor_enabled: true },
    },
    {
      id: "http_timeout",
      label: "Timeout (ms)",
      widget: "number",
      default: 30000,
      min_value: 0,
      step: 1000,
      help_text: "Request timeout in milliseconds",
      section: "HTTP Options",
      tab: "Execution",
    },
    {
      id: "http_max_retries",
      label: "Max Retries",
      widget: "number",
      default: 3,
      min_value: 0,
      max_value: 10,
      help_text: "Maximum number of retry attempts for failed requests",
      section: "HTTP Options",
      tab: "Execution",
    },
    {
      id: "http_retry_delay",
      label: "Retry Delay (ms)",
      widget: "number",
      default: 1000,
      min_value: 0,
      step: 100,
      help_text: "Initial delay between retries",
      section: "HTTP Options",
      tab: "Execution",
    },
    {
      id: "http_backoff_multiplier",
      label: "Backoff Multiplier",
      widget: "number",
      default: 2,
      min_value: 1,
      max_value: 5,
      step: 0.5,
      help_text: "Exponential backoff multiplier for retries",
      section: "HTTP Options",
      tab: "Execution",
    },
    // === Flow Tab ===
    {
      id: "disallow_transfer_to_parent",
      label: "Disallow transfer to parent",
      widget: "checkbox",
      default: false,
      help_text:
        "Prevent this agent from transferring control back to its parent",
      section: "Transfer Controls",
      tab: "Flow",
    },
    {
      id: "disallow_transfer_to_peers",
      label: "Disallow transfer to peers",
      widget: "checkbox",
      default: false,
      help_text:
        "Prevent this agent from transferring control to sibling agents",
      section: "Transfer Controls",
      tab: "Flow",
    },
    // === Schema Tab ===
    {
      id: "output_key",
      label: "Output Key",
      widget: "text",
      default: "",
      placeholder: "e.g., result",
      help_text: "Saves agent output to session state with this key",
      section: "Output Options",
      tab: "Schema",
    },
    {
      id: "include_contents",
      label: "Include Contents",
      widget: "select",
      default: "default",
      options: [
        { value: "default", label: "Default" },
        { value: "none", label: "None" },
      ],
      help_text: "Controls content inclusion in agent processing",
      section: "Output Options",
      tab: "Schema",
    },
    {
      id: "input_schema",
      label: "Input Schema",
      widget: "text",
      default: "",
      placeholder: "e.g., models.TaskInput",
      help_text: "Pydantic BaseModel class path",
      section: "Schema Validation",
      tab: "Schema",
    },
    {
      id: "output_schema",
      label: "Output Schema",
      widget: "text",
      default: "",
      placeholder: "e.g., models.TaskOutput",
      help_text: "Pydantic BaseModel class path",
      section: "Schema Validation",
      tab: "Schema",
    },
    // === Callbacks Tab ===
    {
      id: "before_model_callback",
      label: "Before Model Callback",
      widget: "text",
      default: "",
      placeholder: "e.g., callbacks/guardrails.py",
      help_text: "Callback function to run before model invocation",
      section: "Model Callbacks",
      tab: "Callbacks",
    },
    {
      id: "after_model_callback",
      label: "After Model Callback",
      widget: "text",
      default: "",
      placeholder: "e.g., callbacks/logging.py",
      help_text: "Callback function to run after model invocation",
      section: "Model Callbacks",
      tab: "Callbacks",
    },
    {
      id: "before_tool_callback",
      label: "Before Tool Callback",
      widget: "text",
      default: "",
      placeholder: "e.g., callbacks/validation.py",
      help_text: "Callback function to run before tool execution",
      section: "Tool Callbacks",
      tab: "Callbacks",
    },
    {
      id: "after_tool_callback",
      label: "After Tool Callback",
      widget: "text",
      default: "",
      placeholder: "e.g., callbacks/artifact_save.py",
      help_text: "Callback function to run after tool execution",
      section: "Tool Callbacks",
      tab: "Callbacks",
    },
  ],
};

// Custom model uses the same fields as the default model (full feature set)
const CUSTOM_MODEL_SCHEMA: ModelSchema = {
  ...GEMINI_2_5_FLASH_SCHEMA,
  modelId: "custom",
  label: "Custom",
};

// =============================================================================
// MODEL REGISTRY
// =============================================================================

/**
 * Registry of all model schemas.
 * Each model has its own complete definition.
 */
const MODEL_SCHEMAS: Record<string, ModelSchema> = {
  "gemini-3-flash-preview": GEMINI_3_FLASH_PREVIEW_SCHEMA,
  "gemini-3-pro-preview": GEMINI_3_PRO_PREVIEW_SCHEMA,
  "gemini-2.5-flash": GEMINI_2_5_FLASH_SCHEMA,
  "gemini-2.5-pro": GEMINI_2_5_PRO_SCHEMA,
  "gemini-2.0-flash-exp": GEMINI_2_0_FLASH_EXP_SCHEMA,
  "gemini-2.0-flash": GEMINI_2_0_FLASH_SCHEMA,
  custom: CUSTOM_MODEL_SCHEMA,
};

/**
 * Default schema used for unknown models.
 */
const DEFAULT_SCHEMA = GEMINI_2_5_FLASH_SCHEMA;

// =============================================================================
// EXPORTS
// =============================================================================

/**
 * Get the schema for a specific model.
 * Falls back to default schema for unknown models.
 */
export function getModelSchema(modelId: string): ModelSchema {
  return MODEL_SCHEMAS[modelId] || DEFAULT_SCHEMA;
}

/**
 * Get the list of universal field IDs.
 */
export function getUniversalFieldIds(): string[] {
  return UNIVERSAL_FIELD_IDS;
}

/**
 * Get fields for a specific model.
 */
export function getModelFields(modelId: string): FieldDefinition[] {
  return getModelSchema(modelId).fields;
}

/**
 * Get tabs for a specific model.
 */
export function getModelTabs(modelId: string): string[] {
  return getModelSchema(modelId).tabs;
}

/**
 * Build default config values for a model.
 */
export function getModelDefaults(modelId: string): Record<string, unknown> {
  const schema = getModelSchema(modelId);
  const defaults: Record<string, unknown> = {};

  for (const field of schema.fields) {
    if (field.default !== undefined) {
      defaults[field.id] = field.default;
    }
  }

  return defaults;
}
